# Generated by Django 4.0 on 2021-12-31 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datavis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='content',
            new_name='tagline',
        ),
    ]
