# Generated by Django 4.0 on 2021-12-31 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datavis', '0002_rename_content_page_tagline'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('file', models.FileField(null=True, upload_to='files/')),
                ('date_published', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('tagline', models.CharField(max_length=255)),
                ('date_published', models.DateTimeField(verbose_name='date published')),
                ('x_value', models.CharField(max_length=255, null=True)),
                ('y_value', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(choices=[('live', 'Live'), ('draft', 'Draft')], max_length=11)),
                ('document_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='graph_document_file', to='datavis.file')),
            ],
        ),
    ]
