# Generated by Django 4.0 on 2021-12-31 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datavis', '0003_file_graph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='x_value',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='graph',
            name='y_value',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
