# Generated by Django 4.0 on 2021-12-31 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datavis', '0004_alter_graph_x_value_alter_graph_y_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='menu_order',
            field=models.IntegerField(default=1),
        ),
    ]
