# Generated by Django 4.0 on 2022-01-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datavis', '0005_graph_menu_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graph',
            name='x_value',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='y_value',
        ),
        migrations.AddField(
            model_name='graph',
            name='type',
            field=models.CharField(choices=[('xy', 'XY'), ('pie', 'Pie'), ('radar', 'Radar'), ('map', 'Map'), ('hierarchy', 'Hierarchy'), ('flow', 'Flow'), ('word', 'Word'), ('venn', 'Venn')], default='xy', max_length=11),
        ),
    ]
